[package]
name = "ser"
version = "0.1.0"
edition = "2024"

[dependencies]
hash_cons = "0.2.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0"

isl-rs = "0.1.3"

[build-dependencies]
bindgen = "0.71.1"
